### ISSUE TITLE
Support for new ZWO cameras (SDK 1.2.4 released June 2022)

### ISSUE THREAD

**Issue by CSPhobos** [OpenPHDGuiding/phd2#1001]
I have a new ZWO ASI 662MC camera and it is not working with the current PHD2 software, probably due to old SDK drivers as this camera was just released. Their new SDK was released about two months ago.

The ZWO SDK with the latest drivers is available here: https://download.astronomy-imaging-camera.com/download/asi-camera-sdk-linux-mac/

**Comment by bwdev01** [comment]
Ok, we’ll look into this.  In the meantime you should be able to use the ASCOM camera driver or you could even try using the updated SDK file.  The latter would basically be a “smoke test” – it might work or it might not depending on whether there are breaking changes in the new SDK.

 

Bruce

 

From: Ian Harker ***@***.***> 
Sent: Saturday, August 13, 2022 8:57 PM
To: OpenPHDGuiding/phd2 ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [OpenPHDGuiding/phd2] Support for new ZWO cameras (SDK 1.2.4 released June 2022) (Issue #1001)

 

I have a new ZWO ASI 662MC camera and it is not working with the current PHD2 software, probably due to old SDK drivers as this camera was just released. Their new SDK was released about two months ago.

The ZWO SDK with the latest drivers is available here: https://download.astronomy-imaging-camera.com/download/asi-camera-sdk-linux-mac/

**Comment by agalasso** [comment]
fixed by #1005
