### ISSUE TITLE
PHD2 loses connection with mount

### ISSUE THREAD

**Issue by juandanielmorcilloregueiro** [OpenPHDGuiding/phd2#1013]
Hi,

I´m using PHD2 2.6.11dev2 with INDI 1.9.8 and KStars. After a few minutes guiding, PHD2 shows a message saying that connection with mount was lost. I found this in the logs:

03:12:50.982 00.001 547902897152 Moving (0.24, 0.16) raw xDistance=-0.14 yDistance=-0.25
03:12:50.982 00.000 547902897152 GuideAlgorithmHysteresis::Result() returns 0.00 from input -0.14
03:12:50.982 00.000 547902897152 GuideAlgorithmResistSwitch::result() returns -0.25 from input -0.25
03:12:50.982 00.000 547902897152 MoveAxis(E, 0, ABG)
03:12:50.983 00.001 547902897152 Move returns status 0, amount 0
03:12:50.983 00.000 547902897152 MoveAxis(N, 108, ABG)
03:12:50.983 00.000 547902897152 INDI Mount: pulse guide properties unavailable!
03:12:50.984 00.001 547902897152 Error thrown from /home/astropi3/AstroRoot/phd2/scope.cpp:769->guide failed
03:12:50.984 00.000 547902897152 Move returns status 1, amount 0
03:12:50.984 00.000 547902897152 Error thrown from /home/astropi3/AstroRoot/phd2/worker_thread.cpp:322->Move failed
03:12:50.985 00.001 547902897152 move complete, result=1
03:12:50.985 00.000 547902897152 worker thread done servicing request

I don´t know if it is an issue of PHD2 or INDI. In the previous version of KStars (with PHD2 v2.6.11) I didn´t have any issue.

Do you know what can be the issue? I will try to get logs of INDI.

Thanks.

**Comment by bwdev01** [comment]
Please post these sorts of problems on the  OpenPHDGuiding forum rather than on GitHub.  https://groups.google.com/g/open-phd-guiding

 

You will also need to post the log files in their entirety using the built-in PHD2 log uploading tool:

 

https://openphdguiding.org/getting-help/

 

I’m going to close this issue on GitHub in the expectation you will move the discussion thread to our support forum. 

 

Regards,

Bruce

 

From: Juan Daniel Morcillo ***@***.*** 
Sent: Saturday, October 15, 2022 11:17 AM
To: OpenPHDGuiding/phd2 ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [OpenPHDGuiding/phd2] PHD2 loses connection with mount (Issue #1013)

 

Hi,

I´m using PHD2 2.6.11dev2 with INDI 1.9.8 and KStars. After a few minutes guiding, PHD2 shows a message saying that connection with mount was lost. I found this in the logs:

03:12:50.982 00.001 547902897152 Moving (0.24, 0.16) raw xDistance=-0.14 yDistance=-0.25
03:12:50.982 00.000 547902897152 GuideAlgorithmHysteresis::Result() returns 0.00 from input -0.14
03:12:50.982 00.000 547902897152 GuideAlgorithmResistSwitch::result() returns -0.25 from input -0.25
03:12:50.982 00.000 547902897152 MoveAxis(E, 0, ABG)
03:12:50.983 00.001 547902897152 Move returns status 0, amount 0
03:12:50.983 00.000 547902897152 MoveAxis(N, 108, ABG)
03:12:50.983 00.000 547902897152 INDI Mount: pulse guide properties unavailable!
03:12:50.984 00.001 547902897152 Error thrown from /home/astropi3/AstroRoot/phd2/scope.cpp:769->guide failed
03:12:50.984 00.000 547902897152 Move returns status 1, amount 0
03:12:50.984 00.000 547902897152 Error thrown from /home/astropi3/AstroRoot/phd2/worker_thread.cpp:322->Move failed
03:12:50.985 00.001 547902897152 move complete, result=1
03:12:50.985 00.000 547902897152 worker thread done servicing request

I don´t know if it is an issue of PHD2 or INDI. In the previous version of KStars (with PHD2 v2.6.11) I didn´t have any issue.

Do you know what can be the issue? I will try to get logs of INDI.

Thanks.
