### ISSUE TITLE
event server API enhancement: accept declination and side-of-pier parameters to guide method

### ISSUE THREAD

**Issue by GoogleCodeExporter** [OpenPHDGuiding/phd2#220]
```
When PHD2 is being controlled by a client like SGP, the client may know the 
mount's declination and side of pier, even if PHD2 does not.

We should allow clients to tell PHD2 the declination and side of pier when 
invoking the quide method. That will allow phd2 to scale the calibration and 
flip calibration if necessary.

```

Original issue reported on code.google.com by `andy.gal...@gmail.com` on 3 Dec 2013 at 8:48

**Comment by kkretzschmar** [comment]
I have the same requirement, meaning setting the declination or side of pier of the aux mount equipment via the event server api. I am not sure about the status of this enhancement request... is it already possible? At least I didn't find the RPC method call in the documentation.

Background: I cannot use the Aux mount INDI driver since on the same host an indigo server is already connected to the mount, so I use the "Ask for coordinates" mode of the Aux mount.  The client which controls the event server does have all necessary pointing information.

**Comment by agalasso** [comment]
> I cannot use the Aux mount INDI driver since on the same host an indigo server is already connected to the mount

@kkretzschmar this is the first I have heard of an INDI setup that does not allow multiple INDI clients (one of which is PHD2). Seem like an issue with your INDI setup. I'd recommend seeing if you can get this resolved on the INDI side.

I am going to keep this issue closed.

**Comment by SteveBz** [comment]
Hi @kkretzschmar,
  
  
   
  
  
   If instead of "Ask for coordinates" you choose the Indi option 'INDI mount' it'll give you a dialogue box.  Enter the IP address of the Indi server (eg 192.168.1.nnn) and leave the port defaulted.  If it doesn't show you the mount under drivers, then you probably haven't set it up in Indi.
  
  
   
  
  
   There are several ways to do this, but the easiest is to use http://192.168.1.nnn:8624/ in your browser and it should bring up the INDI Web Manager.  You then choose the driver for your mount and it should then be available from PHD2.
  
  
   
  
  
   I don't recall if it was necessary to install this separately, but Andy is right, Indi is your next port of call.  I have multiple clients in Windows and Linux concurrently using both PHD2 server and Indi on a remote Raspberry Pi running Linux.
  
  
   
  
  
   Have a good day.
  
  
   
  
  
   Regards,
  
  
   
  
  
   Steve.
  
  
   
    On 14/02/2021 22:33 kkretzschmar <notifications@github.com> wrote:
   
   
    
   
   
    
   
   
    
   
   
    I have the same requirement, meaning setting the declination or side of pier of the aux mount equipment via the event server api. I am not sure about the status of this enhancement request... is it already possible? At least I didn't find the RPC method call in the documentation.
   
   
    Background: I cannot use the Aux mount INDI driver since on the same host an indigo server is already connected to the mount, so I use the "Ask for coordinates" mode of the Aux mount. The client which controls the event server does have all necessary pointing information.

**Comment by kkretzschmar** [comment]
> I'd recommend seeing if you can get this resolved on the INDI side.

Problem solved, thanks!. PHD2 INDI client can connect to an indigo server, and I can connect with the INDI aux mount equipment. 

I never tried to connect with an INDI client to an indigo server ...  and fortunately it works, great!

**Comment by kkretzschmar** [comment]
Not sure if you have heard about the Indigo development, here is a link

https://www.indigo-astronomy.org/

I was concerned about running two INDI servers (INDI and Indigo) on the same host, not running several INDI clients against the same server. But as I found out, I don't need to run several servers ... Thanks!

**Comment by SteveBz** [comment]
No I haven't.  It looks very nice.  Is it mainly Apple focused?

Regards,

Steve.

**Comment by kkretzschmar** [comment]
>Is it mainly Apple focused?

No coverage is the same as with legacy INDI: Linux, MacOS, Windows, though native indigo servers does not run on windows,

Indigo has a more modern software architecture leading to less memory and cpu consumption while speeding up runtime performance. That's the reason why I am using it ... 

https://www.indigo-astronomy.org/faq.html

Btw, event server api runs perfectly ... great stuff!!

**Comment by d33psky** [comment]
As someone who witnessed the start of this rewrite happen I'll add some context that I've also shared elsewhere already but not here yet : 
Indigo is a rewrite from the ground up with a different license so that it can be sold in appstores that reject the GPL license.
This license difference also means that none of the INDI device drivers can ever be part of Indigo.
However Indigo can still talk the 'INDI' network protocol to a real INDI server that has the INDI device drivers loaded.
The license difference and a disagreement with the original INDI protocol spec author on things like a speed improvement led to its birth.
And I develop for INDI, not for Indigo.
-- Hans

**Comment by SteveBz** [comment]
You call INDI 'legacy' are you saying indigo is a replacement for INDI?

Actually, I wrote my own event broker for INDI using RabbitMQ on Raspberry.  But I use it to wrap the event server for PHD2 as well, otherwise I need several different standards for different products. 

Sorry, this is all a bit off topic :)

Steve.

**Comment by kkretzschmar** [comment]
> You call INDI 'legacy' are you saying indigo is a replacement for INDI?

No, Indigo is another implementation of the INDI protocol with some extensions as Hans pointed out. Sorry if my wording led to confusions ...

 >Sorry, this is all a bit off topic :)

Agree this should be discussed somewhere else :-)
Klaus
