### ISSUE TITLE
QHY cameras: allow selecting which camera when multiple cameras are connected

### ISSUE THREAD

**Issue by GoogleCodeExporter** [OpenPHDGuiding/phd2#432]
```
Currently phd2 always connects to the first QHY camera discovered, but we 
should allow the user to choose the camera when more than one camera is 
connected.

```

Original issue reported on code.google.com by `andy.gal...@gmail.com` on 13 May 2015 at 6:34

**Comment by d33psky** [comment]
Is this still valid ?

**Comment by agalasso** [comment]
yes, I believe it is still valid.  It has been addressed in the phd_qhy fork, but I do not see that fork being merged any time soon since QHY has apparently lost interest in supporting non-ASCOM camera access.

Let's keep it open because it documents a legitimate issue with the native QHY support currently available in PHD2.
