### ISSUE TITLE
ASCOM driver for QHY5 camera returns mangled sub-frames

### ISSUE THREAD

**Issue by bwdev01** [OpenPHDGuiding/phd2#446]
User reports that using sub-frames with the ASCOM camera connection for the QHY5 results in mangled sub-frames.  Full frames work correctly.  Extensive debug information is available on the related OpenPHD2 forum thread from Giovanni.

**Comment by agalasso** [comment]
we probably cannot do anything about this in phd2 since it appears to be a problem with the QHY ASCOM driver. subframes work fine in PHD2 with all the other ASCOM drivers we know of.

It should be very simple to write a script that retrieves a full frame and a subframe from the camera to demonstrate the problem is independent from phd2.

**Comment by bwdev01** [comment]
Problem not reproducible, no further comment from OP in 7 months.
