### ISSUE TITLE
Drift align tool needs a stop slew button

### ISSUE THREAD

**Issue by agalasso** [OpenPHDGuiding/phd2#470]
Message from Fred in the stark labs forum:

The other night I was using the Drift Align wizard (very nice, by the way) and accidently entered the wrong sign in the box Slew To - Meridian off set.  The scope proceeded to do an unexpected meridian flip.  I had to dash around to the mount controller to stop the motion. 

I suggest that the Drift Align wizard add a STOP button.

Fred Klein

**Comment by bwdev01** [comment]
FWIW, I agree completely with the need.  But I probably would do an 'Abort'
dialog during the slew rather than a 'Stop' button.  When the scope is
heading off into a ditch, it can be hard to find a button on the UI - been
there, done that :-(.  Whereas with an Abort dialog sitting right there in
your face, it's easier.  Also, the dialog wouldn't create any new real
estate or layout challenges.
 
Bruce
 
  _____
