### ISSUE TITLE
INDI cannot connect On-camera mount (sometimes)

### ISSUE THREAD

**Issue by agalasso** [OpenPHDGuiding/phd2#626]
Steps to reproduce:
  select INDI Camera, configure to connect to INDI CCD Simulator
  Select ON-camera for Mount
  click Connect All
 phd2 reports "Mount Connect Failed"
  sometimes it works though, and I'm not sure what sequence of steps make the difference

**Comment by pchev** [comment]
This must be fixed by 05705297a81ec50ac863b419b74796e90f535c69 
Can you check if it work better now, because I cannot reproduce the problem on my system.

**Comment by agalasso** [comment]
It was reproducing reliably for me with an INDI server running on my Linux PC, and connecting from a remote Windows system running PHD2.   With the change, it not longer reproduces, so closing as fixed.
Thanks Patrick!
It is unfortunate that the fix requires an arbitrary wait. Is that a limitation of the protocol that there is not a way to know that there are no more properties to come?

**Comment by pchev** [comment]
The problem is because this properties are send only after the device is physically connected to the indi driver, this is normally done when you click the Connect button. Then the server send all the camera properties but there is no signal when the last one is received. This is not a problem for the mandatory properties we check before to set "modal", but for the optional like the pulse guiding it is not possible to know if it will come later or not.

Another option is to always set m_hasGuideOutput for the indi camera, it will return an error at the first guide command if not supported by the camera.

**Comment by agalasso** [comment]
I emailed Jasem and CC'd you.  Let's see what he says.
