### ISSUE TITLE
BLC-induced oscillation

### ISSUE THREAD

**Issue by agalasso** [OpenPHDGuiding/phd2#667]
![image](https://user-images.githubusercontent.com/6864470/34645500-23c1bec6-f31d-11e7-87ed-e1ba03c8e623.png)

[PHD2_DebugLog_2018-01-06_181007.txt](https://github.com/OpenPHDGuiding/phd2/files/1609409/PHD2_DebugLog_2018-01-06_181007.txt)
[PHD2_GuideLog_2018-01-06_181007.txt](https://github.com/OpenPHDGuiding/phd2/files/1609410/PHD2_GuideLog_2018-01-06_181007.txt)

**Comment by bwdev01** [comment]
Those guide pulses on the graph represent a sum of the blc + normal guide
correction.  The blc pulse-size was not being adjusted at those two times -
note that the raw south offsets were increasing at those two points so the
summation simply got larger.  So I don't see a problem with the algo.  You
can also see a history of under-corrections, many instances where a
blc+normal adjustment is followed by a normal adjustment in the same
direction.  That's why the blc pulses were generally being adjusted upward
during this time interval, excluding the two points you're looking at.  So I
don't see a problem beyond the fact that the mount is ill-suited for using
backlash comp and may, as you said, have a backlash comp active in the
firmware.
 
Bruce
  _____

**Comment by agalasso** [comment]
thanks Bruce, that makes sense.

**Comment by bwdev01** [comment]
Well, it was a plausible explanation, but not apparently the right one. :-(  The mount apparently has a large amount of stiction and stored energy return, resulting in instability (see thread).   We should be able to avoid repeatedly increasing the blc amount in the face of this kind of response although actually compensating for it may be impractical.

**Comment by bwdev01** [comment]
Backlash comp adjustment re-written in 2.6.4.dev10 to handle stiction-related issues.
