### ISSUE TITLE
disable dec algo graph window controls when dec guide mode is None

### ISSUE THREAD

**Issue by agalasso** [OpenPHDGuiding/phd2#816]
as a visual cue indicating that dec guiding is disabled

https://groups.google.com/d/topic/open-phd-guiding/rymJkkRppes/discussion

**Comment by bwdev01** [comment]
Feature Request #816 – Disable algo graph window controls when Dec guide mode is none

Expanded to apply same treatment for changes made within the AD – updates to both the graph window and the algo params in the AD mount pane

Enumeration of test cases:

Change to Dec guide mode (‘None’ or otherwise) made in GraphPane
	Enable/Disable graph pane Dec guide parameters
	
Change to Dec guide mode via any call to SetDecGuideMode
	Enable/Disable graph pane Dec guide parameters

Change to Dec guide mode via any interface will be reflected in next display of AD with Dec guide params enabled/disabled

Change to Dec guide mode inside Advanced Dialog
	Immediately enable/disable Dec guide parameters displayed in the Mount algo panel
	Enable/disable Dec graph pane controls after AD is closed with ‘ok’

Change to Dec guide algo selection in Advanced Dialog
	Enable/disable of Dec guide parameters in newly selected algo based on state of Dec guide mode control in the AD panel –   not necessarily the in-use Dec guide mode
