### ISSUE TITLE
Guidestar wander

### ISSUE THREAD

**Issue by starhopper-de** [OpenPHDGuiding/phd2#874]
I am usind PHD more than a decade with great success, good work, many thanks!!!

My setup is a 12" f/4 newton on a Skywatcher EQ8 mount and a off-axis guider with a ASI 120 USB3 guiding cam. PHD Linux version and EQMOD. Guiding works perfect, no single frame fails.

I have attached a screenshoot, in which I marked the star position at the beginning of the session with a bookmark. After some time and dithers, the star wanders, with the result that I have to crop my image later. In this case there where 100 images (dithers). I am using random dither.

I suppose there maybe a bug. In my eyes the new position after dither should be calculated from the starting position, not from the recent position. Am I right, or is there another thing in my setup?

![PHD Star wandering](https://user-images.githubusercontent.com/44210083/90057030-1a490700-dce0-11ea-8b5e-c331c38e25ef.jpg)

**Comment by bwdev01** [comment]
Hi Thomas.  Dithers are always treated as relative offsets from the
*current* lock-position and it has always worked that way.  In fact, a
dither is created by simply changing the value of the lock-position and
letting the guide algorithms move the guide star to that location.  There is
no history kept of prior lock positions.  If you are doing large dithers and
are worried about the net drift of the lock position over long time periods,
you should use the spiral mode of dithering - that's really why that mode
was added.  In my experience, dithering nearly always results in some
cropping along the margins of the stacked frame because those areas
necessarily have a lower SNR than the rest of the frame.  
 
Cheers,
Bruce
 
  _____

**Comment by starhopper-de** [comment]
Hello Bruce,
thank you very much for your detailed answer. My english is rather poor, but I understand, that this behavour is normal operation. I expected that new dither position were always calculated from the start position ( when I press the green button) of guiding or a special lock-position.
So, all star wandering resulting from refraction, bad mount and polar alignment accumulate during guiding pauses (autofocus, dither and so on). I will use spiral dither next time I had to do more than 50 frames per session. 

Cheers,
Thomas
www.starhopper.eu
