### ISSUE TITLE
Select which ZWO camera is your guiding camera

### ISSUE THREAD

**Issue by welzen7963** [OpenPHDGuiding/phd2#987]
I have a problem when starting PHD2 that the wrong camera is selected as my guiding camera. I have ZWO cameras. My guide camera is a ZWO ASI 120mm mini (3.75µm pixel size). My imaging camera is a ZWO ASI 294MC Pro (4.63µm pixel size). When starting PHD2 the ASI294MC Pro is always selected as the guide camera. I can tell the ASI 294MC Pro is selected by the camera pixel size shown in PHD2. I tried to change the pixel size from 4.63µm to 3.75µm but cannot because the field is grayed out. I first thought PHD2 might be selecting the the ASI 294MC Pro because the ASI 120mm mini was plugged into the ASI 294MC Pro and PHD2 could not detect the difference between the to cameras. I changed the setup to have both cameras plugged into separate USB ports on my hub but the ASI 294MC Pro was still selected as the guiding camera. I then tried only the ASI 120mm mini with PHD2; that worked. I then plugged in my ASI 294MC Pro into my hub and the ASI 120mm mini was still shown as the guide camera. Now, my work-around is to start PHD2 with only the ASI 120mm mini camera connected and after PHD2 is running then connect my ASI 294MC Pro. Would it be possible to be able to select which camera is the guide camera in the case of using ZWO cameras for both guiding and imaging? If you have any questions please contact me. Thanks! Brent

**Comment by bvalente22** [comment]
HI welzen7963
You should be posting these questions on the openphdguiding user group, github is not the place for support
This is a known problem, the workaround if you are using a wizard is to unplug/disable the imaging camera, go through the process, then re-enable it when you are done


Thanks



Brian

-------------------------------------------------------------------------
Brian Valente
brianvalentephotography.com
 

    On Friday, May 13, 2022, 03:40:08 PM PDT, welzen7963 ***@***.***> wrote:  
 
 


I have a problem when starting PHD2 that the wrong camera is selected as my guiding camera. I have ZWO cameras. My guide camera is a ZWO ASI 120mm mini (3.75µm pixel size). My imaging camera is a ZWO ASI 294MC Pro (4.63µm pixel size). When starting PHD2 the ASI294MC Pro is always selected as the guide camera. I can tell the ASI 294MC Pro is selected by the camera pixel size shown in PHD2. I tried to change the pixel size from 4.63µm to 3.75µm but cannot because the field is grayed out. I first thought PHD2 might be selecting the the ASI 294MC Pro because the ASI 120mm mini was plugged into the ASI 294MC Pro and PHD2 could not detect the difference between the to cameras. I changed the setup to have both cameras plugged into separate USB ports on my hub but the ASI 294MC Pro was still selected as the guiding camera. I then tried only the ASI 120mm mini with PHD2; that worked. I then plugged in my ASI 294MC Pro into my hub and the ASI 120mm mini was still shown as the guide camera. Now, my work-around is to start PHD2 with only the ASI 120mm mini camera connected and after PHD2 is running then connect my ASI 294MC Pro. Would it be possible to be able to select which camera is the guide camera in the case of using ZWO cameras for both guiding and imaging? If you have any questions please contact me. Thanks! Brent
