### ISSUE TITLE
Integrating PHD2 with new protocols

### ISSUE THREAD

**Issue by MattBlack85** [OpenPHDGuiding/phd2#997]
Hi people, I am working on a personal project where I am trying to build a complete suite for astrophotography/drivers that will work on the three major platforms. I am a couple of light-years away from adding autoguiding but I would like to think about this integration withy my stuff (worth noting, this is not ASCOM, ALPACA nor INDI) so I can properly plan my server.
Ideally I would love PHD2 to be only an image analyser, meaning I ship pics to it, it makes calculations returning back the correction I should apply but from what I read in the issues this is not possible at this time so I am wondering in my case what would be the right way to integrate phd2 into my app?

**Comment by bwdev01** [comment]
Astro-imaging is best accomplished by using independently-written programs that are "best-of-breed" at what they do - image capture, guiding, automating, plate-solving, whatever.  In order for that to work, they need to comply with the standards that have been developed for cooperation, mostly communication protocols.  This is particularly true for mount control.  If you think you're going to write all-new drivers for every mount that has ever been built, you are more than a few light-years away from getting there.  That's why PHD2 uses the industry standards for mount communication - ASCOM, INDI, and no doubt Alpaca in the future.  If you're planning on writing a driver just for your particular mount, you should do that using one of these standards.  In order to use PHD2 in the suite you're planning, you can write a driver for your mount and then write your capture/automation apps to use the PHD2 server interface to control how PHD2 manages guiding for you. Many of us have done all that.  Or you can use whatever driver has already been written for your mount. That's how most of the automation apps work today.  Mount control and feedback is fundamental to what PHD2 does and we're not going to do anything to reduce or eliminate that.  Of course PHD2 is open-source, so you can download all the source and do whatever you want in a "private" version of the app.   But it will be forever-private, we wouldn't merge that back into the mainstream branch - you would be on your own.

Bruce

**Comment by MattBlack85** [comment]
@bwdev01 thanks for chiming in.

No offence but it seems you are mostly judging my ideas here.
I have my very own motivations to do what I am doing, the existing protocols have all problems, especially when it comes to data mining, extending them or providing a true multiplatform experience; except for ALPACA which is anyway rewriting all drivers around but they will be ASCOM compliant so it's a no got for me.

I have already 3 drivers working on MacOS, Linux and Windows, a pegasus ppba, zwo ccd and zwo efw, this week I am starting the eqmod one and then I will move to writing the app/server for my protocol.
I don't want to write _now_ all drivers for any existing product as it would have no sense, I just wanna write a couple to start a POC and validate my ideas and from there eventually moving forward/backward.

```Mount control and feedback is fundamental to what PHD2 does and we're not going to do anything to reduce or eliminate that. Of course PHD2 is open-source, so you can download all the source and do whatever you want in a "private" version of the app. But it will be forever-private, we wouldn't merge that back into the mainstream branch ```

it's not very clear why such a thought, I don't think I ever said something like that, especially at this point in time where I don't have basically anything. I am very much aware that I will need to fork and work on my branch and I am pretty fine with this, at the end of the day this is still a poc, but still something I wanna do!

I am not very comfortable with phd2 code base at the moment but it is my understanding that more or less what happens under the hood is phd2 is running a client (at least for INDI) that talks to the mount, I am only seeking for guidance on which area of the project I shuld look ar so I can prepare my poc, hence my question.

PS: I don't particularly care where my project will go, the experience I am building spending time on it is so massive that even if it will stop at an early stage I will much more than satisfied

**Comment by bwdev01** [comment]
Well, you asked about the best way to integrate PHD2 into your app and I gave you that advice - use the existing server interface.  Tearing PHD2 apart to remove all mount interactions makes no sense to me and I don't know how you would do that.  If you’ve invented a proprietary way of communicating with mounts, you can add a new class of ‘scope’ in PHD2 along the lines of the scope_ascom and scope-indi classes.
